### ISSUE TITLE
Tensorboard dimension mismatch

### ISSUE THREAD

**Issue by enisimsar** [OctThe16th/FIGR#2]
In `validation_run` method in `train.py`, at line 99 and 115 np.expand_dims method create an unnecessary dimension. It causes the following error.

```Traceback (most recent call last):
  File "train.py", line 223, in <module>
    env.training()
  File "train.py", line 165, in training
    self.validation_run()
  File "train.py", line 120, in validation_run
    self.writer.add_image('Validation_generated', img, self.eps)
  File ".../tensorboardX/writer.py", line 427, in add_image
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime)
  File ".../tensorboardX/summary.py", line 211, in image
    tensor = convert_to_HWC(tensor, dataformats)
  File ".../tensorboardX/utils.py", line 98, in convert_to_HWC
    assert(len(tensor.shape) == len(input_format)), "size of input tensor and input format are different"
AssertionError: size of input tensor and input format are different
```

`add_image`  method has the `dataformats` parameter and its default value is CHW (channel-height-width). The code sends a four-dimensional tensor to the `add_image` method. example: (1, 1, 32, 32) [not necessary dimension and causes an error, CHANNEL, HEIGHT, WIDTH]

I tried with all supported datasets. 
```
python train.py --dataset Omniglot
python train.py --dataset Mnist
python train.py --dataset FIGR8
```

I will send a pull request that resolves this issue.

**Comment by luxinfeng** [comment]
hello, i met the same question, did you solve it?

**Comment by enisimsar** [comment]
yes, you can look at #3

**Comment by luxinfeng** [comment]
OK ,thank you .

**Comment by harkiratbehl** [comment]
how did you solve it? I would appreciate that you write proper answers before closing an issue
